name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install root dependencies
        run: npm ci
      - name: Install
        run: npm ci --prefix relay
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test --prefix relay
