name: Release

on:
  push:
    branches:
      - main
      - 'feat/**'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: relay/Dockerfile
          target: production
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/figma-relay:${{ github.sha }}

      - name: Smoke test /health
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/figma-relay
        run: |
          set -euo pipefail
          trap 'docker rm -f relay-smoke >/dev/null 2>&1 || true' EXIT
          docker run -d --rm --name relay-smoke -p 3000:3000 "$IMAGE_NAME:${GITHUB_SHA}"
          for attempt in $(seq 1 20); do
            if curl -fsS http://localhost:3000/health > /tmp/health.txt; then
              cat /tmp/health.txt
              break
            fi
            sleep 2
          done
          curl -fsS http://localhost:3000/health

      - name: Stop smoke container
        if: always()
        run: docker rm -f relay-smoke >/dev/null 2>&1 || true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/figma-relay
        run: |
          set -euo pipefail
          docker push "$IMAGE_NAME:${GITHUB_SHA}"
          if [ "${{ github.ref_protected }}" = "true" ]; then
            docker tag "$IMAGE_NAME:${GITHUB_SHA}" "$IMAGE_NAME:latest"
            docker push "$IMAGE_NAME:latest"
          fi
