name: Release

on:
  push:
    branches:
      - main
      - 'feat/**'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: |
            relay/package-lock.json

      - name: Compute image repo (lowercase) and short SHA
        id: meta
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"
          echo "owner_lc=$OWNER_LC" >> "$GITHUB_OUTPUT"
          echo "image_repo=ghcr.io/$OWNER_LC/figma-relay" >> "$GITHUB_OUTPUT"
          echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Install dependencies (relay)
        run: npm ci --prefix relay

      - name: Run lint
        run: npm --prefix relay run lint

      - name: Run tests (CI)
        run: npm run test:ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & load (production)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: relay/Dockerfile
          target: production
          load: true
          tags: |
            ${{ steps.meta.outputs.image_repo }}:${{ steps.meta.outputs.short_sha }}

      - name: Smoke test container
        run: |
          docker run -d --rm -p 3000:3000 --name relay ${{ steps.meta.outputs.image_repo }}:${{ steps.meta.outputs.short_sha }}
          sleep 3
          curl -fsS http://localhost:3000/health
          docker rm -f relay

      - name: Docker login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (production)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: relay/Dockerfile
          target: production
          push: true
          tags: |
            ${{ steps.meta.outputs.image_repo }}:${{ steps.meta.outputs.short_sha }}
            ${{ steps.meta.outputs.image_repo }}:latest
